//! `sonar code install` — writes a `.git/hooks/post-merge` hook that
//! re-indexes the repo whenever a merge (which `git pull` performs after
//! fetching) lands on the configured branch. Mirrors the design of the
//! transcript-side SessionEnd hook: hook fires on a deliberate "the past
//! has just become canonical" event, not on every file change.

use anyhow::{Context, Result};
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

/// Write `.git/hooks/post-merge` in `repo` so that `git pull` /
/// `git merge` on `branch` triggers `sonar code index`.
///
/// Idempotent: if a `# sonar-code` marker is already present in an
/// existing hook, the hook is rewritten in place; otherwise a fresh
/// hook is created. Any pre-existing hook is backed up to
/// `post-merge.pre-sonar` on first install.
pub fn install_post_merge_hook(repo: &Path, branch: &str) -> Result<()> {
    let repo = repo
        .canonicalize()
        .with_context(|| format!("canonicalizing {}", repo.display()))?;
    let git_dir = repo.join(".git");
    if !git_dir.exists() {
        anyhow::bail!(
            "not a git repo: {} (no .git directory found)",
            repo.display()
        );
    }
    let hooks_dir = git_dir.join("hooks");
    fs::create_dir_all(&hooks_dir)?;
    let hook_path = hooks_dir.join("post-merge");

    let bin = std::env::current_exe()?;
    let bin_str = bin.to_string_lossy().to_string();
    let label = repo
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("repo");

    let hook = format!(
        r#"#!/bin/bash
# sonar-code post-merge hook — reindexes the repo when a merge lands on the
# tracked branch. Generated by `sonar code install`. Safe to delete.
set -e
BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)
if [ "$BRANCH" = "{branch}" ]; then
  "{bin}" code index --repo "{repo}" --label "{label}" --branch "{branch}" >/dev/null 2>&1 &
fi
"#,
        branch = branch,
        bin = bin_str,
        repo = repo.display(),
        label = label,
    );

    if hook_path.exists() {
        let existing = fs::read_to_string(&hook_path).unwrap_or_default();
        if existing.contains("# sonar-code post-merge hook") {
            // Already ours — rewrite in case bin path or branch changed.
            fs::write(&hook_path, &hook)?;
        } else {
            // Back up the user's hook so we don't trample it.
            let backup = hooks_dir.join("post-merge.pre-sonar");
            if !backup.exists() {
                fs::copy(&hook_path, &backup)?;
            }
            // Append-style merge: keep their hook, add ours below.
            let merged = format!("{}\n\n{}", existing.trim_end(), hook);
            fs::write(&hook_path, merged)?;
        }
    } else {
        fs::write(&hook_path, &hook)?;
    }

    // Ensure executable.
    let mut perms = fs::metadata(&hook_path)?.permissions();
    perms.set_mode(0o755);
    fs::set_permissions(&hook_path, perms)?;

    println!("installed: {}", hook_path.display());
    println!("  fires on: `git pull` / `git merge` while on `{}`", branch);
    println!("  re-indexes: {} (label: {})", repo.display(), label);
    println!();
    println!(
        "to test now: cd {} && touch .sonar-trigger && git pull --no-rebase",
        repo.display()
    );
    Ok(())
}
